### ISSUE TITLE
Off Topic: Dalao NiuBee

### ISSUE THREAD

**Issue by noahzark** [iceynano/nikke_fishing#1]
We have a qq group for discussing nikke scripts like this repo, would you like to join us?
base64: ODIzMjY1ODA3

**Comment by iceynano** [comment]
![Screenshot_20240710-001451_TIM.png](https://github.com/iceynano/nikke_fishing/assets/34570144/f75d7398-96e6-4a2e-ae2f-61ea87102339)

**Comment by noahzark** [comment]
the zhumi group master is blamed and took fully responsilbe for the incident.
please try again.
