### ISSUE TITLE
not working after update

### ISSUE THREAD

**Issue by gfernandez-me** [iceynano/nikke_fishing#2]
they change the fishing game

they said its smooth now but the script is not working anymore

**Comment by iceynano** [comment]
please describe issue you meet precisely; if you could upload screen recording with clear console output and full game window, it would be useful for finding what exactly happened.

**Comment by gfernandez-me** [comment]
I'm losing all the time after the last update
its getting bad bad bad
![f2](https://github.com/iceynano/nikke_fishing/assets/5313969/93441263-ff13-4084-9afc-7faca0ea1f03)
![f1](https://github.com/iceynano/nikke_fishing/assets/5313969/f5aa3f3f-38ed-47e5-b368-83c9437973bb)

**Comment by gfernandez-me** [comment]
I tried main branch and dev branch, same result

this started happening after they announced they changed the fishing game to made it easier

**Comment by iceynano** [comment]
you could try comment out this line:

https://github.com/iceynano/nikke_fishing/blob/2b42667b78051b39f2b88d6ef95ac12d2c523f1a/run.py#L273

if the problem persists, please check your CPU running frequency. if it is too low, it may cause a significant decrease in performance

**Comment by iceynano** [comment]
Oops. I noticed that you are not running script as admin privilege, please read README very carefully.
